# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63734a5c743b55408535a5cf60d33cdcccbb1bd9d1c567bf95412c8131e95d55ba8201b187b53de255ebaf900db519706c71ef3c52d41eabf98570b993b287b1

test:
  secret_key_base: 3930809a4fa45acf7b7c333ebf26d083c7130d46d71d58c81c7827a50d084d17ef971cfe12ce6bbe062fb44e5a7f1b5c71515084b07ec94a2fd2706cd9e103b4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
